server:
  port: 9090

property:
  test:
    name: property depth test
propertyTest: test
propertyTestList: a,b,c

fruit:
  list:
    - name: banana
      color: yellow
    - name: apple
      color: red
    - name: water melon
      color: green
  colorName: pink

spring:
  h2:
    console:
      enabled: true
      path: /h2-test

datasource:
#    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: sa

---
spring:
  profiles: local
server:
  port: 8080
---
spring:
  profiles: real
server:
  port: 8082